apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 21600
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t2.small", "t2.medium"]
  provider:
    launchTemplate: karpenter-cpu
    subnetSelector:
      vpc: k8s_vpc
      Tier: private
